name: test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pre-commit
          key: {% raw %}${{ runner.os }}-pip-0{% endraw %}
          restore-keys: |
            {% raw %}${{ runner.os }}-pip-{% endraw %}
            {% raw %}${{ runner.os }}-{% endraw %}
      - run: python -m pip install pre-commit
      - run: pre-commit run --all-files
  test:
    needs: linting
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.7", "3.8", "3.9" ]
        flake8-version: [ "1", "2", "3" ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up python {% raw %}${{ matrix.python-version }}{% endraw %}
        uses: actions/setup-python@v2
        with:
          python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
      - name: Install poetry
        uses: snok/install-poetry@v1.1.2
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: .venv
          key: {% raw %}${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-0{% endraw %}
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - run: {% raw %}pip install flake8==${{ matrix.flake8-version }}{% endraw %}
      - name: Install package
        run: poetry install --no-interaction
      - name: Run tests
        run: |
          source .venv/bin/activate
          poetry run pytest --cov={{ cookiecutter.project_slug }} --verbose --assert=plain
          poetry run coverage report